# Generated by Django 2.0.6 on 2018-10-11 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Musical',
            new_name='Timeapp',
        ),
    ]
